name: Build

on:
  push:
    branches: [ "test-ci" ]
  pull_request:
    branches: [ "test-ci" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [ "Debug", "Release" ]

    steps:
    - uses: actions/checkout@v4

    # from https://stackoverflow.com/questions/79852888/
    - name: Install Visual Studio Build Tools
      shell: pwsh
      run: |
        Write-Host "Installing VS 2026 Build Tools..."
        choco install visualstudio2026buildtools `
          --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --includeRecommended --quiet" `
          -y --ignore-package-exit-codes=3010
        Write-Host "VS 2026 Build Tools installation completed" 

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\Common7\Tools\VsDevCmd.bat"
        msbuild /m /p:Configuration=${{ matrix.config }} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}
