name: Build & Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2025-vs2026
    strategy:
      matrix:
        config: [ "Debug", "Release" ]

    steps:
    - uses: actions/checkout@v6

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{ matrix.config }} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'

    - name: Install MyPy
      run: pip install mypy
    - name: Validate testrunner
      run: mypy --strict tests/test.py

    - name: Run Tests
      run: python tests/test.py x64\${{ matrix.config }}\llisp.exe
